name: test and get result on commit


on:
  workflow_dispatch:
    
    inputs:
      node-version:
        description: 'Node version'
        required: false
        type: string
        default: 14.x
        


jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello this is testing install and test Node.js ${{ inputs.node-version }}"

  test:
    name: Yarn test
    if: github.event_name == 'pull_request'
    runs-on:
      group: ubuntu-runners
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3

      - name: Install Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version}}
      
      - name: check coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          # test-script: yarn jest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: building step
        run: echo "Hello ${{ inputs.node-version }}"
      

